// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDzQdZZjeGOmtetqJZKzvD_P26HVipk2Y',
    appId: '1:951495042438:web:42b7828cc92c06f7ebb807',
    messagingSenderId: '951495042438',
    projectId: 'prueba2-999b7',
    authDomain: 'prueba2-999b7.firebaseapp.com',
    storageBucket: 'prueba2-999b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWSl-1J0cBJkcWkuoC_BsCDsDsIcb0-jI',
    appId: '1:951495042438:android:a3752b28e3408cb4ebb807',
    messagingSenderId: '951495042438',
    projectId: 'prueba2-999b7',
    storageBucket: 'prueba2-999b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAviDl16l1FWrZuEdRdc-3Tj4hH4AZPY7A',
    appId: '1:951495042438:ios:3f6dce1534cc2bb4ebb807',
    messagingSenderId: '951495042438',
    projectId: 'prueba2-999b7',
    storageBucket: 'prueba2-999b7.appspot.com',
    iosBundleId: 'com.rnlf.prueba2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAviDl16l1FWrZuEdRdc-3Tj4hH4AZPY7A',
    appId: '1:951495042438:ios:94ce251619f0e899ebb807',
    messagingSenderId: '951495042438',
    projectId: 'prueba2-999b7',
    storageBucket: 'prueba2-999b7.appspot.com',
    iosBundleId: 'com.rnlf.prueba2.RunnerTests',
  );
}
